/**
 * Order query functions.
 * All mutations run inside a caller-supplied transaction client.
 * snake_case DB columns → camelCase JSON via SQL aliases.
 */
import { incrementUsage } from './voucher.queries.js';

// ── createOrderWithItems ───────────────────────────────────────────────────────

/**
 * Create an order, insert all items, decrement stock, create payment,
 * and clear the user's cart — all inside a transaction.
 *
 * @param {import('pg').PoolClient} client  Already-connected transaction client
 * @param {object} opts
 * @returns {Promise<{ orderId: number, orderNo: string }>}
 */
export async function createOrderWithItems(client, {
    userId, addressId,
    shipName, shipPhone, shipAddress, shipCity,
    subtotal, shippingFee, discountAmount = 0, total,
    items,
    method,
    voucherId = null,
    pointsUsed = 0,
    pointsDiscount = 0,
}) {
    // 1. Insert order (order_no auto-generated by trigger)
    const { rows: orderRows } = await client.query(`
        INSERT INTO orders
            (user_id, address_id, ship_name, ship_phone, ship_address, ship_city,
             subtotal, shipping_fee, discount_amount, total, total_amount, status, voucher_id, points_used, points_discount)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10, 'pending', $11, $12, $13)
        RETURNING id, order_no AS "orderNo"
    `, [userId, addressId, shipName, shipPhone, shipAddress, shipCity,
        subtotal, shippingFee, discountAmount, total, voucherId, pointsUsed, pointsDiscount]);

    const { id: orderId, orderNo } = orderRows[0];

    // 2. Batch insert order_items
    for (const item of items) {
        await client.query(`
            INSERT INTO order_items
                (order_id, variant_id, product_name, color_name, size_label, sku,
                 quantity, unit_price, total_price)
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        `, [orderId, item.variantId, item.productName, item.colorName,
            item.sizeLabel, item.sku, item.quantity, item.unitPrice, item.totalPrice]);
    }

    // 3. Decrement stock for each variant
    for (const item of items) {
        await client.query(`
            UPDATE product_variants
            SET    stock = stock - $1
            WHERE  id = $2
        `, [item.quantity, item.variantId]);
    }

    // 4. Create payment record
    await client.query(`
        INSERT INTO payments (order_id, method, amount, status)
        VALUES ($1, $2, $3, 'pending')
    `, [orderId, method, total]);

    // 5. Clear user's cart
    await client.query(`
        DELETE FROM cart_items
        WHERE cart_id = (
            SELECT id FROM carts WHERE user_id = $1 LIMIT 1
        )
    `, [userId]);

    // 6. Increment voucher usage if applicable
    if (voucherId) {
        await incrementUsage(client, voucherId);
    }

    return { orderId, orderNo };
}

// ── getOrdersByUser ────────────────────────────────────────────────────────────

/**
 * List orders for a user with pagination.
 *
 * @param {import('pg').Pool} pool
 * @param {{ userId: number, page: number, limit: number }} opts
 * @returns {Promise<{ orders: Array, total: number }>}
 */
export async function getOrdersByUser(pool, { userId, page, limit }) {
    const offset = (page - 1) * limit;

    const { rows } = await pool.query(`
        SELECT
            o.id,
            o.order_no          AS "orderNo",
            o.status,
            o.subtotal,
            o.shipping_fee      AS "shippingFee",
            o.total,
            o.created_at        AS "createdAt",
            COUNT(oi.id)        AS "itemCount",
            p.method            AS "paymentMethod",
            p.status            AS "paymentStatus"
        FROM   orders o
        LEFT JOIN order_items oi ON oi.order_id = o.id
        LEFT JOIN payments    p  ON p.order_id  = o.id
        WHERE  o.user_id = $1
        GROUP  BY o.id, p.method, p.status
        ORDER  BY o.created_at DESC
        LIMIT  $2 OFFSET $3
    `, [userId, limit, offset]);

    const { rows: countRows } = await pool.query(
        `SELECT COUNT(*) FROM orders WHERE user_id = $1`,
        [userId],
    );

    return { orders: rows, total: parseInt(countRows[0].count, 10) };
}

// ── getOrderById ──────────────────────────────────────────────────────────────

/**
 * Fetch a single order with all its items and payment.
 *
 * @param {import('pg').Pool} pool
 * @param {{ orderId: number, userId: number }} opts
 * @returns {Promise<object|null>}
 */
export async function getOrderById(pool, { orderId, userId }) {
    const { rows } = await pool.query(`
        SELECT
            o.id,
            o.order_no          AS "orderNo",
            o.status,
            o.subtotal,
            o.shipping_fee      AS "shippingFee",
            o.total,
            o.ship_name         AS "shipName",
            o.ship_phone        AS "shipPhone",
            o.ship_address      AS "shipAddress",
            o.ship_city         AS "shipCity",
            o.note,
            o.created_at        AS "createdAt",
            o.updated_at        AS "updatedAt",
            COALESCE(
                json_agg(
                    json_build_object(
                        'id',          oi.id,
                        'variantId',   oi.variant_id,
                        'productName', oi.product_name,
                        'colorName',   oi.color_name,
                        'sizeLabel',   oi.size_label,
                        'sku',         oi.sku,
                        'quantity',    oi.quantity,
                        'unitPrice',   oi.unit_price,
                        'totalPrice',  oi.total_price
                    ) ORDER BY oi.id
                ) FILTER (WHERE oi.id IS NOT NULL),
                '[]'
            )                   AS items,
            row_to_json(
                (SELECT r FROM (
                    SELECT p.id, p.method, p.status, p.amount,
                           p.transaction_id AS "txnId", p.paid_at AS "paidAt"
                    FROM payments p WHERE p.order_id = o.id LIMIT 1
                ) r)
            )                   AS payment
        FROM   orders o
        LEFT JOIN order_items oi ON oi.order_id = o.id
        WHERE  o.id = $1 AND o.user_id = $2
        GROUP  BY o.id
    `, [orderId, userId]);

    return rows[0] ?? null;
}

// ── cancelOrder ───────────────────────────────────────────────────────────────

/**
 * Cancel an order only if it is still in 'pending' status.
 *
 * @returns {Promise<object|null>} Updated order row or null
 */
export async function cancelOrder(pool, { orderId, userId }) {
    const { rows } = await pool.query(`
        UPDATE orders
        SET    status = 'cancelled', updated_at = NOW()
        WHERE  id = $1 AND user_id = $2 AND status = 'pending'
        RETURNING id, order_no AS "orderNo", status
    `, [orderId, userId]);
    return rows[0] ?? null;
}

// ── confirmPayment ────────────────────────────────────────────────────────────

/**
 * Mark payment as paid and update order status to 'confirmed'.
 * Runs inside its own transaction.
 *
 * @returns {Promise<{ orderId: number }>}
 */
export async function confirmPayment(pool, { orderId, txnId, gatewayData }) {
    const client = await pool.connect();
    try {
        await client.query('BEGIN');

        await client.query(`
            UPDATE payments
            SET    status = 'paid',
                   transaction_id = $2,
                   gateway_data   = $3,
                   paid_at        = NOW()
            WHERE  order_id = $1
        `, [orderId, txnId, gatewayData ? JSON.stringify(gatewayData) : null]);

        await client.query(`
            UPDATE orders
            SET    status = 'confirmed', updated_at = NOW()
            WHERE  id = $1
        `, [orderId]);

        await client.query('COMMIT');
        return { orderId };
    } catch (err) {
        await client.query('ROLLBACK');
        throw err;
    } finally {
        client.release();
    }
}

// ── adminListOrders ───────────────────────────────────────────────────────────

/**
 * Admin: paginated list of all orders with user + payment info.
 * Optional status filter.
 *
 * @returns {Promise<{ orders: Array, total: number }>}
 */
export async function adminListOrders(pool, { status, page, limit }) {
    const offset = (page - 1) * limit;
    const params = [limit, offset];
    let where = '';

    if (status) {
        params.push(status);
        where = `WHERE o.status = $${params.length}`;
    }

    const { rows } = await pool.query(`
        SELECT
            o.id,
            o.order_no          AS "orderNo",
            o.status,
            o.total,
            o.created_at        AS "createdAt",
            u.email             AS "userEmail",
            u.full_name         AS "userFullName",
            p.method            AS "paymentMethod",
            p.status            AS "paymentStatus"
        FROM   orders o
        JOIN   users    u ON u.id = o.user_id
        LEFT JOIN payments p ON p.order_id = o.id
        ${where}
        ORDER  BY o.created_at DESC
        LIMIT  $1 OFFSET $2
    `, params);

    const countParams = status ? [status] : [];
    const countWhere = status ? `WHERE status = $1` : '';
    const { rows: countRows } = await pool.query(
        `SELECT COUNT(*) FROM orders ${countWhere}`,
        countParams,
    );

    return { orders: rows, total: parseInt(countRows[0].count, 10) };
}

// ── adminUpdateOrderStatus ───────────────────────────────────────────────────

/**
 * Admin: update order status and append to status log.
 * Uses transaction.
 *
 * @returns {Promise<object>} Updated order row
 */
export async function adminUpdateOrderStatus(pool, { orderId, status, changedBy }) {
    const client = await pool.connect();
    try {
        await client.query('BEGIN');

        const { rows } = await client.query(`
            UPDATE orders
            SET    status = $2, updated_at = NOW()
            WHERE  id = $1
            RETURNING id, order_no AS "orderNo", status, updated_at AS "updatedAt"
        `, [orderId, status]);

        if (!rows[0]) throw Object.assign(new Error('Order not found'), { status: 404, code: 'NOT_FOUND' });

        await client.query(`
            INSERT INTO order_status_log (order_id, status, changed_by)
            VALUES ($1, $2, $3)
        `, [orderId, status, changedBy ?? null]);

        await client.query('COMMIT');
        return rows[0];
    } catch (err) {
        await client.query('ROLLBACK');
        throw err;
    } finally {
        client.release();
    }
}
